
platform :ios, '9.0'
use_frameworks!
target 'ClothingSecurity' do
    pod 'Album', :path => 'submodules/Album/'
    pod 'MediaEditorKit', :path => 'submodules/MediaEditorKit/'
    pod 'SnapKit', :path => 'submodules/SnapKit/'
    pod 'ReactiveSwift', :path => 'submodules/ReactiveSwift/'
    pod 'HUD', :path =>'submodules/HUD/'
    pod 'Mesh', :path =>'submodules/Mesh/'
    pod 'SwiftyJSON', :path => 'submodules/SwiftyJSON/'
    pod 'XCGLogger', :path => 'submodules/XCGLogger/'
    pod 'ESTabBarController', :path =>'submodules/ESTabBarController/'
    pod 'Eureka', :path =>'submodules/Eureka/'
    pod 'Core', :path => 'submodules/Core/'
    pod 'ReactiveObjC', :path =>'submodules/ReactiveObjC/'
    pod 'ReactiveCocoa', :path =>'submodules/ReactiveCocoa/'
    pod 'Result', :path =>'submodules/Result/'
    pod 'FDFullscreenPopGesture', :path =>'submodules/FDFullscreenPopGesture/'
    pod 'AlertController', :path =>'submodules/AlertController/'
    pod 'PopoverImagePicker', :path =>'submodules/PopoverImagePicker/'
    pod 'ActionSheet', :path =>'submodules/ActionSheet/'
    pod 'PinLayout', :path => 'submodules/PinLayout/'
    pod 'MJRefresh', :path => 'submodules/MJRefresh/'
end
