source 'http://114.55.33.22/ios/SpecsSwift4.git'

target 'Mesh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!

  pod 'ReactiveSwift'
  pod 'XCGLogger'
end

target 'MestTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveSwift'
  # Pods for MestTest

end
