source 'http://180.166.126.162:9000/ios/SpecsSwift4.git'
# platform :ios, '9.0'

target 'AlertController' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlertController
  pod 'SnapKit', '~> 3.2.0'
  
end

target 'TestAlertController' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlertController
  pod 'SnapKit', '~> 3.2.0'
  
end

