source 'http://gitlab.xiaoheiban.cn/ios/SpecsSwift4.git'
# platform :ios, '8.0'

target 'MediaEditorKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'pop'

end

target 'Test' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    pod 'pop'
end
